  spring:
    config:
      import: optional:application-secret.yaml
    application:
      name: financeapp
    datasource:
      # Connection URL (Default PostgreSQL port is 5432)
      url: jdbc:postgresql://localhost:5432/cam
      username: postgres
      password:
      driver-class-name: org.postgresql.Driver
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update
      show-sql: true
    # used for adding default values into data service class
    app:
      use:
        default: true
    logging:
      config:
        classpath: logback.xml
    security:
      oauth2:
        client:
          registration:
#            google:
#              client-id:
#              client-secret:
#              scope:
            github:
              client-id: Ov23liwKSXDeZenKXoav
              client-secret: ${GITHUB_CLIENT_SECRET}
              scope:
                - read:user
                - user:email