-- Table: test.accounts

-- DROP TABLE IF EXISTS test.accounts;

CREATE TABLE IF NOT EXISTS test.accounts
(
    account_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    provider_id character varying(255) COLLATE pg_catalog."default",
    username character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    settings character varying(255) COLLATE pg_catalog."default",
    url character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT accounts_pkey PRIMARY KEY (account_id),
    CONSTRAINT accounts_provider_id_unique UNIQUE (provider_id)
    )

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS test.accounts
    OWNER to postgres;