-- Table: test.accounts

-- DROP TABLE IF EXISTS test.accounts;

CREATE TABLE IF NOT EXISTS test.accounts
(
    account_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    provider_id VARCHAR(255),
    username VARCHAR(255),
    name VARCHAR(255),
    settings VARCHAR(255),

    CONSTRAINT accounts_pkey PRIMARY KEY (account_id),
    CONSTRAINT accounts_provider_id_unique UNIQUE (provider_id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS test.accounts
    OWNER to postgres;